"""init

Revision ID: 760a9842f5b6
Revises: 
Create Date: 2026-09-02 16:27:50.631553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '760a9842f5b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('menu',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_menus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('menu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menu_type', sa.Enum('DIRECTORY', 'MENU', name='menutype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('route_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon_type', sa.Enum('ICONIFY', 'LOCAL', name='menuicontype'), nullable=False),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.Column('hide_in_menu', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('i18n_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keep_alive', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('multi_tab', sa.Boolean(), nullable=False),
    sa.Column('fixed_index_in_tab', sa.Integer(), nullable=True),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('interfaces', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_menus_created_by'), 'menu_menus', ['created_by'], unique=False)
    op.create_index(op.f('ix_menu_menus_id'), 'menu_menus', ['id'], unique=False)
    op.create_index(op.f('ix_menu_menus_route_name'), 'menu_menus', ['route_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_menus_route_name'), table_name='menu_menus')
    op.drop_index(op.f('ix_menu_menus_id'), table_name='menu_menus')
    op.drop_index(op.f('ix_menu_menus_created_by'), table_name='menu_menus')
    op.drop_table('menu_menus')
    # ### end Alembic commands ###
