"""init

Revision ID: c3e63df08148
Revises:
Create Date: 2026-04-09 15:41:32.951736

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3e63df08148"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_crontab_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("minute", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day_of_week", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day_of_month", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("month_of_year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_crontab_schedule_id"), "celery_crontab_schedule", ["id"], unique=False)
    op.create_table(
        "celery_interval_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("every", sa.Integer(), nullable=False),
        sa.Column(
            "period",
            sa.Enum("WEEKS", "DAYS", "HOURS", "MINUTES", "SECONDS", "MILLISECONDS", "MICROSECONDS", name="period"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_interval_schedule_id"), "celery_interval_schedule", ["id"], unique=False)
    op.create_table(
        "celery_periodic_task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_type", sa.Enum("INTERVAL", "CRONTAB", "SOLAR", name="tasktype"), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_periodic_task_id"), "celery_periodic_task", ["id"], unique=False)
    op.create_table(
        "celery_solar_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column(
            "event",
            sa.Enum(
                "DAWN_ASTRONOMICAL",
                "DAWN_NAUTICAL",
                "DAWN_CIVIL",
                "SUNRISE",
                "SOLAR_NOON",
                "SUNSET",
                "DUSK_CIVIL",
                "DUSK_NAUTICAL",
                "DUSK_ASTRONOMICAL",
                name="solarevent",
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Integer(), nullable=False),
        sa.Column("longitude", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_solar_schedule_id"), "celery_solar_schedule", ["id"], unique=False)
    op.create_table(
        "celery_task_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("task_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "STARTED", "SUCCESS", "FAILURE", "RETRY", "REVOKED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("worker_hostname", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("runtime", sa.Float(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("logs", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_task_results_id"), "celery_task_results", ["id"], unique=False)
    op.create_index(op.f("ix_celery_task_results_task_id"), "celery_task_results", ["task_id"], unique=True)
    op.create_index(op.f("ix_celery_task_results_task_name"), "celery_task_results", ["task_name"], unique=False)
    op.create_index(
        op.f("ix_celery_task_results_worker_hostname"), "celery_task_results", ["worker_hostname"], unique=False
    )
    op.create_table(
        "celery_workers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("status", sa.Enum("ONLINE", "OFFLINE", name="workerstatus"), nullable=False),
        sa.Column("active_queues", sa.JSON(), nullable=True),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column("processed_count", sa.Integer(), nullable=False),
        sa.Column("active_task_count", sa.Integer(), nullable=False),
        sa.Column("load_average", sa.JSON(), nullable=True),
        sa.Column("software_info", sa.JSON(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celery_workers_hostname"), "celery_workers", ["hostname"], unique=True)
    op.create_index(op.f("ix_celery_workers_id"), "celery_workers", ["id"], unique=False)
    op.create_table(
        "manage_menus",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("menu_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("menu_type", sa.Enum("DIRECTORY", "MENU", name="menutype"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("route_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("route_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("component", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon_type", sa.Enum("ICONIFY", "LOCAL", name="menuicontype"), nullable=False),
        sa.Column("status", sa.Enum("ON", "OFF", name="status"), nullable=False),
        sa.Column("hide_in_menu", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("i18n_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keep_alive", sa.Boolean(), nullable=False),
        sa.Column("constant", sa.Boolean(), nullable=False),
        sa.Column("href", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("multi_tab", sa.Boolean(), nullable=False),
        sa.Column("fixed_index_in_tab", sa.Integer(), nullable=True),
        sa.Column("query", sa.JSON(), nullable=True),
        sa.Column("buttons", sa.JSON(), nullable=True),
        sa.Column("interfaces", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manage_menus_id"), "manage_menus", ["id"], unique=False)
    op.create_index(op.f("ix_manage_menus_route_name"), "manage_menus", ["route_name"], unique=True)
    op.create_table(
        "manage_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("status", sa.Enum("ON", "OFF", name="status"), nullable=False),
        sa.Column("interface_permissions", sa.JSON(), nullable=True),
        sa.Column("button_permissions", sa.JSON(), nullable=True),
        sa.Column("router_permissions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_manage_roles_id"), "manage_roles", ["id"], unique=False)
    op.create_table(
        "manage_routers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_manage_routers_id"), "manage_routers", ["id"], unique=False)
    op.create_table(
        "manage_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.Enum("ON", "OFF", name="status"), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_manage_users_id"), "manage_users", ["id"], unique=False)
    op.create_table(
        "script_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("script_id", sa.Uuid(), nullable=False),
        sa.Column("executor_id", sa.Uuid(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=False),
        sa.Column("runtime", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_script_executions_executor_id"), "script_executions", ["executor_id"], unique=False)
    op.create_index(op.f("ix_script_executions_id"), "script_executions", ["id"], unique=False)
    op.create_index(op.f("ix_script_executions_script_id"), "script_executions", ["script_id"], unique=False)
    op.create_table(
        "scripts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("ON", "OFF", name="status"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_scripts_id"), "scripts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scripts_id"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_script_executions_script_id"), table_name="script_executions")
    op.drop_index(op.f("ix_script_executions_id"), table_name="script_executions")
    op.drop_index(op.f("ix_script_executions_executor_id"), table_name="script_executions")
    op.drop_table("script_executions")
    op.drop_index(op.f("ix_manage_users_id"), table_name="manage_users")
    op.drop_table("manage_users")
    op.drop_index(op.f("ix_manage_routers_id"), table_name="manage_routers")
    op.drop_table("manage_routers")
    op.drop_index(op.f("ix_manage_roles_id"), table_name="manage_roles")
    op.drop_table("manage_roles")
    op.drop_index(op.f("ix_manage_menus_route_name"), table_name="manage_menus")
    op.drop_index(op.f("ix_manage_menus_id"), table_name="manage_menus")
    op.drop_table("manage_menus")
    op.drop_index(op.f("ix_celery_workers_id"), table_name="celery_workers")
    op.drop_index(op.f("ix_celery_workers_hostname"), table_name="celery_workers")
    op.drop_table("celery_workers")
    op.drop_index(op.f("ix_celery_task_results_worker_hostname"), table_name="celery_task_results")
    op.drop_index(op.f("ix_celery_task_results_task_name"), table_name="celery_task_results")
    op.drop_index(op.f("ix_celery_task_results_task_id"), table_name="celery_task_results")
    op.drop_index(op.f("ix_celery_task_results_id"), table_name="celery_task_results")
    op.drop_table("celery_task_results")
    op.drop_index(op.f("ix_celery_solar_schedule_id"), table_name="celery_solar_schedule")
    op.drop_table("celery_solar_schedule")
    op.drop_index(op.f("ix_celery_periodic_task_id"), table_name="celery_periodic_task")
    op.drop_table("celery_periodic_task")
    op.drop_index(op.f("ix_celery_interval_schedule_id"), table_name="celery_interval_schedule")
    op.drop_table("celery_interval_schedule")
    op.drop_index(op.f("ix_celery_crontab_schedule_id"), table_name="celery_crontab_schedule")
    op.drop_table("celery_crontab_schedule")
    # ### end Alembic commands ###
