/* oxlint-disable @typescript-eslint/no-explicit-any */
import path from "path"
import { fileURLToPath } from "url"
import { HmrContext } from "vite"
import crypto from "crypto"
import fs from "fs"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/** TODO: refactor current plugins */
export function generateI18nTypes() {
  const localesDir = path.resolve(__dirname, "../../src/locales/langs")
  const outFile = path.resolve(__dirname, "../../src/typings/i18n.d.ts")
  const langs = fs.readdirSync(localesDir).filter((f) => fs.statSync(path.join(localesDir, f)).isDirectory())

  const result: Record<string, Set<string>> = {}

  fs.readdirSync(localesDir).forEach((lang) => {
    const langDir = path.join(localesDir, lang)
    if (!fs.statSync(langDir).isDirectory()) return

    fs.readdirSync(langDir).forEach((file) => {
      const ns = path.basename(file, ".json")
      const content = JSON.parse(fs.readFileSync(path.join(langDir, file), "utf-8"))

      if (!result[ns]) result[ns] = new Set()
      collectKeys(content, "", result[ns])
    })
  })

  function collectKeys(obj: any, prefix: string, keys: Set<string>) {
    for (const key in obj) {
      const fullKey = prefix ? `${prefix}.${key}` : key
      const value = obj[key]
      if (typeof value === "object" && value !== null && !Array.isArray(value)) {
        collectKeys(value, fullKey, keys)
      } else {
        keys.add(fullKey)
      }
    }
  }

  let output = `/* Auto-generated by gen-i18n-types. Do not edit manually. */\n`

  output += `/* oxlint-disable @typescript-eslint/no-explicit-any */\n\n`
  output += `declare namespace I18nKeys {\n`

  const namespaces = Object.keys(result)

  namespaces.forEach((ns) => {
    const keys = Array.from(result[ns]).sort()

    output += `  type ${ns} =\n    | ${keys.map((k) => `"${k}"`).join("\n    | ")}\n\n`
  })

  output += `}\n`

  output += `type I18nFullKey =\n  ${namespaces.map((ns) => `| \`${ns}.\${I18nKeys.${ns}}\``).join("\n  ")}\n\n`

  output += `declare namespace I18n {\n`
  output += `  type LangType = ${langs.map((l) => `"${l}"`).join(" | ")}\n\n`
  output += `  type LangOption = {\n`
  output += `    label: string\n`
  output += `    key: LangType\n`
  output += `  }\n\n`
  output += `  type TranslateOptions<Locales extends string = LangType> = import("vue-i18n").TranslateOptions<Locales>\n\n`
  output += `  interface $T {\n`
  output += `    (key: I18nFullKey): string\n`
  output += `    (key: I18nFullKey, plural: number, options?: TranslateOptions<LangType>): string\n`
  output += `    (key: I18nFullKey, defaultMsg: string, options?: TranslateOptions<I18nFullKey>): string\n`
  output += `    (key: I18nFullKey, list: unknown[], options?: TranslateOptions<I18nFullKey>): string\n`
  output += `    (key: I18nFullKey, list: unknown[], plural: number): string\n`
  output += `    (key: I18nFullKey, list: unknown[], defaultMsg: string): string\n`
  output += `    (key: I18nFullKey, named: Record<string, unknown>, options?: TranslateOptions<LangType>): string\n`
  output += `    (key: I18nFullKey, named: Record<string, unknown>, plural: number): string\n`
  output += `    (key: I18nFullKey, named: Record<string, unknown>, defaultMsg: string): string\n`
  output += `  }\n`
  output += `}\n`

  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, output)

  console.log("i18n.d.ts generated!")
}

export function generateI18nTypesPlugin() {
  const localesDir = path.resolve(__dirname, "../../src/locales/langs")

  let lastHash = ""

  const runGenerator = () => {
    try {
      generateI18nTypes()
    } catch (e) {
      console.error("[i18n] Type generation failed:", e)
    }
  }

  const calculateHash = () => {
    const files = fs
      .readdirSync(localesDir, { recursive: true })
      .filter((f) => String(f).endsWith(".json"))
      .map((f) => path.join(localesDir, String(f)))

    return crypto
      .createHash("sha256")
      .update(files.map((f) => fs.readFileSync(f)).join(""))
      .digest("hex")
  }

  return {
    name: "vite-plugin-generate-i18n-types",

    buildStart() {
      if (process.env.NODE_ENV !== "development") return
      console.log("[i18n] Generating types on build start...")
      lastHash = calculateHash()
      runGenerator()
    },

    handleHotUpdate(ctx: HmrContext) {
      if (process.env.NODE_ENV !== "development") return

      const file = ctx.file
      if (!file.endsWith(".json")) return
      if (!path.resolve(file).startsWith(localesDir)) return

      const newHash = calculateHash()
      if (newHash === lastHash) return
      lastHash = newHash

      console.log(`[i18n] Locale file changed: ${file}`)
      runGenerator()
    },
  }
}
