# Auto-generated by gen-i18n-types. Do not edit manually.

from typing import Literal

languages = {"en-US", "zh-CN"}

I18nKey = Literal[
    "auth.error.invalidCredentials",
    "common.response.badRequest",
    "common.response.internalServer",
    "common.response.internalServerDetails",
    "common.response.invalidParameter",
    "common.response.invalidParameterDetails",
    "common.response.invalidParameterMessage",
    "common.response.notFound",
    "common.response.permissionDenied",
    "common.response.resourceAlreadyExists",
    "common.response.success",
    "common.response.unauthorized",
]
