# Auto-generated by gen-i18n-types. Do not edit manually.

from typing import Literal, TypeAlias

LANGUAGE_TYPE: TypeAlias = Literal["en-US", "zh-CN"]

languages: set[LANGUAGE_TYPE] = {"en-US", "zh-CN"}

I18nKey = Literal[
    "auth.error.invalidCredentials",
    "common.response.alreadyExists",
    "common.response.authenticationFailed",
    "common.response.badRequest",
    "common.response.concurrentModification",
    "common.response.databaseError",
    "common.response.dependencyError",
    "common.response.duplicateRequest",
    "common.response.externalServiceError",
    "common.response.insufficientPermissions",
    "common.response.internalServerError",
    "common.response.invalidFormat",
    "common.response.invalidInput",
    "common.response.invalidOperation",
    "common.response.menuInvalidParent",
    "common.response.menuNotFound",
    "common.response.menuOperationError",
    "common.response.menuPermissionDenied",
    "common.response.missingRequiredField",
    "common.response.permissionOperationError",
    "common.response.resourceNotFound",
    "common.response.resourcePermissionDenied",
    "common.response.roleNotFound",
    "common.response.roleOperationError",
    "common.response.rolePermissionDenied",
    "common.response.socketAuthenticationFailed",
    "common.response.socketConnectionClosed",
    "common.response.socketConnectionError",
    "common.response.socketInvalidMessage",
    "common.response.socketMessageSendError",
    "common.response.socketNamespaceNotFound",
    "common.response.stateConflict",
    "common.response.success",
    "common.response.systemBusy",
    "common.response.thirdPartyError",
    "common.response.tokenExpired",
    "common.response.tokenInvalid",
    "common.response.tokenRefreshFailed",
    "common.response.tooManyRequests",
    "common.response.userDisabled",
    "common.response.userNotFound",
    "common.response.userOperationError",
    "common.response.validationError",
]
