import os

from rapidkit_core.log import logger
from watchfiles import awatch

from src.locales.utils import gen_literal_from_dict, load_and_flatten_locales, load_language_namespace, write_py_file


async def watch_locale_files():
    """
    程序化监听本地化文件的更改，并根据需要重新生成类型文件。

    Raises:
        - 文件操作期间可能発生的任何异常，例如 IOError。
        - 与加载或处理本地化数据相关的异常。

    Returns:
        该函数不返回任何值。它的目的是监听更改并更新类型文件。
    """
    base_path = os.path.dirname(__file__)
    lang_path = os.path.join(base_path, "langs")
    types_path = os.path.join(base_path, "types.py")

    async for changes in awatch(lang_path):
        logger.debug("i18n file change: {changes}", changes=changes)

        locales_data = load_and_flatten_locales(lang_path)
        namespaces = load_language_namespace(lang_path)
        languages_literal_type = f"Literal[{', '.join(repr(ns) for ns in namespaces)}]"
        generated_code = "# Auto-generated by gen-i18n-types. Do not edit manually.\n\n"
        generated_code += "from typing import Literal, TypeAlias\n\n"
        generated_code += f"LANGUAGE_TYPE: TypeAlias = {languages_literal_type}\n\n"
        generated_code += f"languages: set[LANGUAGE_TYPE] = {namespaces}\n\n"
        generated_code += gen_literal_from_dict(locales_data["zh-CN"])
        generated_code += "\n"

        write_py_file(types_path, generated_code)
