import logging
import os

from watchfiles import awatch

from src.locales.utils import gen_literal_from_dict, load_and_flatten_locales, load_language_namespace, write_py_file

logger = logging.getLogger(__name__)


async def watch_locale_files():
    """
    Asynchronously watches for changes in localization files and regenerates the types file accordingly.

    Raises:
        - Any exceptions that may occur during file operations, such as IOError.
        - Exceptions related to loading or processing locale data.

    Returns:
        This function does not return any value. Its purpose is to watch for changes and update the types file.
    """
    base_path = os.path.dirname(__file__)
    lang_path = os.path.join(base_path, "langs")
    types_path = os.path.join(base_path, "types.py")

    async for changes in awatch(lang_path):
        logger.debug("i18n file change:", changes)

        result = load_and_flatten_locales(lang_path)

        text = "# Auto-generated by gen-i18n-types. Do not edit manually.\n\n"
        text += "from typing import Literal\n\n"
        text += f"languages = {load_language_namespace(lang_path)}\n\n"
        text += gen_literal_from_dict(result["zh-CN"])
        text += "\n"

        write_py_file(types_path, text)
