import logging
import os

from watchfiles import awatch

from src.locales.utils import gen_literal_from_dict, load_and_flatten_locales, load_language_namespace, write_py_file

logger = logging.getLogger(__name__)


async def watch_locale_files():
    """
    程序化监听本地化文件的更改，并根据需要重新生成类型文件。

    Raises:
        - 文件操作期间可能発生的任何异常，例如 IOError。
        - 与加载或处理本地化数据相关的异常。

    Returns:
        该函数不返回任何值。它的目的是监听更改并更新类型文件。
    """
    base_path = os.path.dirname(__file__)
    lang_path = os.path.join(base_path, "langs")
    types_path = os.path.join(base_path, "types.py")

    async for changes in awatch(lang_path):
        logger.debug("i18n file change:", changes)

        result = load_and_flatten_locales(lang_path)

        text = "# Auto-generated by gen-i18n-types. Do not edit manually.\n\n"
        text += "from typing import Literal\n\n"
        text += f"languages = {load_language_namespace(lang_path)}\n\n"
        text += gen_literal_from_dict(result["zh-CN"])
        text += "\n"

        write_py_file(types_path, text)
