services:
  pytest_postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: pytest_postgres
    hostname: pytest_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 3s
      retries: 5

  pytest_redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: pytest_redis
    hostname: pytest_redis
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
