/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/keys/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Key
         * @description Obtain the public key for RSA encryption of password.
         */
        get: operations["get_public_key_api_v1_auth_keys_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description User login endpoint.
         *
         *     This endpoint validates the user's credentials, decrypts the password,
         *     checks it against the database, and returns access and refresh tokens upon success.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out the current user.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh the user's access token using their refresh token.
         */
        post: operations["refresh_token_api_v1_auth_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description Retrieve the current authenticated user's information.
         *
         *     This endpoint returns detailed information of the user after validating the token
         *     and fetching the full record from the database.
         */
        get: operations["get_user_info_api_v1_auth_user_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/backend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Router
         * @description This endpoint retrieves all routes from the database and returns them in the response.
         */
        get: operations["get_router_api_v1_router_backend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roles
         * @description Get a paginated list of roles.
         */
        get: operations["get_roles_api_v1_roles_get"];
        put?: never;
        /**
         * Create Role
         * @description Create a new role.
         */
        post: operations["create_role_api_v1_roles_post"];
        /**
         * Batch Delete Role
         * @description Delete multiple roles by a list of IDs.
         */
        delete: operations["batch_delete_role_api_v1_roles_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Roles
         * @description Get roles assigned to the current user.
         */
        get: operations["get_my_roles_api_v1_roles_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Roles
         * @description Get a full list of roles without pagination.
         */
        get: operations["get_all_roles_api_v1_roles_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Role
         * @description Update a role by ID.
         */
        put: operations["update_role_api_v1_roles__role_id__put"];
        post?: never;
        /**
         * Delete Role
         * @description Delete a single role by ID.
         */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticationError
         * @description Authentication error response.
         */
        AuthenticationError: {
            /**
             * Code
             * @default 401
             */
            code: number;
            /**
             * Message
             * @default Unauthorized.
             */
            message: string;
            /** Data */
            data?: null;
        };
        /**
         * BadRequestResponse
         * @description Unified Bad request response.
         */
        BadRequestResponse: {
            /**
             * Code
             * @default 400
             */
            code: number;
            /**
             * Message
             * @default Bad request.
             */
            message: string;
            /** Data */
            data?: null;
        };
        /**
         * FastAPIRouterResponse
         * @description Interface router response schema.
         */
        FastAPIRouterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Path */
            path: string;
            /** Methods */
            methods: string[];
            /**
             * Code
             * @description Role interface permission code.
             */
            readonly code: string;
        };
        /**
         * LoginRequest
         * @description Login schemas request.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * NotFoundResponse
         * @description Unified not found response.
         */
        NotFoundResponse: {
            /**
             * Code
             * @default 404
             */
            code: number;
            /**
             * Message
             * @default Not found.
             */
            message: string;
            /** Data */
            data?: null;
        };
        /** PaginatedResponse[RoleResponse] */
        PaginatedResponse_RoleResponse_: {
            /**
             * Page
             * @description Page number.
             */
            page: number;
            /**
             * Pagesize
             * @description Page size.
             */
            pageSize: number;
            /**
             * Total
             * @description Total records.
             */
            total: number;
            /**
             * Records
             * @description Records.
             */
            records: components["schemas"]["RoleResponse"][];
        };
        /**
         * PermissionResponse
         * @description Unified permission response.
         */
        PermissionResponse: {
            /**
             * Code
             * @default 403
             */
            code: number;
            /**
             * Message
             * @default Permission denied.
             */
            message: string;
            /** Data */
            data?: null;
        };
        /** Response[PaginatedResponse[RoleResponse]] */
        Response_PaginatedResponse_RoleResponse__: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /** @description Response data. */
            data?: components["schemas"]["PaginatedResponse_RoleResponse_"] | null;
        };
        /** Response[RoleResponse] */
        Response_RoleResponse_: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /** @description Response data. */
            data?: components["schemas"]["RoleResponse"] | null;
        };
        /** Response[TokenResponse] */
        Response_TokenResponse_: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /** @description Response data. */
            data?: components["schemas"]["TokenResponse"] | null;
        };
        /** Response[UserInfoResponse] */
        Response_UserInfoResponse_: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /** @description Response data. */
            data?: components["schemas"]["UserInfoResponse"] | null;
        };
        /** Response[bool] */
        Response_bool_: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /**
             * Data
             * @description Response data.
             */
            data?: boolean | null;
        };
        /** Response[list[FastAPIRouterResponse]] */
        Response_list_FastAPIRouterResponse__: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /**
             * Data
             * @description Response data.
             */
            data?: components["schemas"]["FastAPIRouterResponse"][] | null;
        };
        /** Response[list[RoleResponse]] */
        Response_list_RoleResponse__: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /**
             * Data
             * @description Response data.
             */
            data?: components["schemas"]["RoleResponse"][] | null;
        };
        /** Response[str] */
        Response_str_: {
            /**
             * Code
             * @description Status code.
             * @default 200
             */
            code: number;
            /**
             * Message
             * @default Successful.
             */
            message: string;
            /**
             * Data
             * @description Response data.
             */
            data?: string | null;
        };
        /**
         * RoleBatchBody
         * @description Queries batch role schema.
         */
        RoleBatchBody: {
            /**
             * Ids
             * @description list of item ids.
             */
            ids: string[];
        };
        /**
         * RoleCreate
         * @description Create role schema.
         */
        RoleCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleResponse
         * @description Role response schema.
         */
        RoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleUpdate
         * @description Update role schema.
         */
        RoleUpdate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * ServerErrorResponse
         * @description Unified server error response.
         */
        ServerErrorResponse: {
            /**
             * Code
             * @default 500
             */
            code: number;
            /**
             * Message
             * @default Http server error.
             */
            message: string;
            /**
             * Data
             * @default Internal Server Error details.
             */
            data: string;
        };
        /**
         * TokenResponse
         * @description Token response.
         */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * UserInfoResponse
         * @description User info schemas response.
         */
        UserInfoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /**
             * Roles
             * @default []
             */
            roles: string[];
            /**
             * Buttons
             * @default []
             */
            buttons: string[];
        };
        /**
         * ValidationErrorResponse
         * @description Unified unprocessable entity response.
         */
        ValidationErrorResponse: {
            /**
             * Code
             * @default 422
             */
            code: number;
            /**
             * Message
             * @default Invalid parameter.
             */
            message: string;
            /**
             * Data
             * @default Validation error details.
             */
            data: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_public_key_api_v1_auth_keys_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_str_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_token_refresh_post: {
        parameters: {
            query?: never;
            header: {
                "x-refresh-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_user_info_api_v1_auth_user_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserInfoResponse_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_router_api_v1_router_backend_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_FastAPIRouterResponse__"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_roles_api_v1_roles_get: {
        parameters: {
            query: {
                /** @description current page number. */
                page: number;
                /** @description number of items per page. */
                pageSize: number;
                keyword?: string;
                status?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_PaginatedResponse_RoleResponse__"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    batch_delete_role_api_v1_roles_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_my_roles_api_v1_roles_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_all_roles_api_v1_roles_all_get: {
        parameters: {
            query?: {
                keyword?: string;
                status?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Invalid parameter. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Http server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
}
