/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/keys/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Key
         * @description 得到用于 RSA 加密密码的公开密钥。
         */
        get: operations["get_public_key_api_v1_auth_keys_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录端点。
         *
         *     该端点验证用户的凭证，解密密码，需验证数据库，并在成功时返回访问令牌和刷新令牌。
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 登出当前用户。
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description 使用刷新令牌刷新用户的访问令牌。
         */
        post: operations["refresh_token_api_v1_auth_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description 检索当前的用户信息。
         *
         *     该端点在验证令牌和从数据库检索了完整记录后需出有详细信息。
         */
        get: operations["get_user_info_api_v1_auth_user_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/backend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Router
         * @description 该端点从数据库检索所有路由并在响应中返回。
         */
        get: operations["get_router_api_v1_router_backend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roles
         * @description 获取分页的角色列表。
         */
        get: operations["get_roles_api_v1_roles_get"];
        put?: never;
        /**
         * Create Role
         * @description 创建一个新角色。
         */
        post: operations["create_role_api_v1_roles_post"];
        /**
         * Batch Delete Role
         * @description 根据 ID 列表删除多个角色。
         */
        delete: operations["batch_delete_role_api_v1_roles_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Roles
         * @description 获取分配给当前用户的角色。
         */
        get: operations["get_my_roles_api_v1_roles_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Roles
         * @description 获取不带分页的完整角色列表。
         */
        get: operations["get_all_roles_api_v1_roles_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Role
         * @description 根据 ID 更新角色。
         */
        put: operations["update_role_api_v1_roles__role_id__put"];
        post?: never;
        /**
         * Delete Role
         * @description 根据 ID 删除单个角色。
         */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticationError
         * @description 认证错误响应。
         */
        AuthenticationError: {
            /**
             * Code
             * @default 401
             */
            code: number;
            /** Message */
            message?: string;
            /** Data */
            data?: null;
        };
        /**
         * BadRequestResponse
         * @description 统一错误请求响应。
         */
        BadRequestResponse: {
            /**
             * Code
             * @default 400
             */
            code: number;
            /** Message */
            message?: string;
            /** Data */
            data?: null;
        };
        /**
         * FastAPIRouterResponse
         * @description 接口路由响应数据结构。
         */
        FastAPIRouterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Path */
            path: string;
            /** Methods */
            methods: string[];
            /**
             * Code
             * @description 角色接口权限编码。
             */
            readonly code: string;
        };
        /**
         * LoginRequest
         * @description 登录请求数据结构。
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * NotFoundResponse
         * @description 统一未找到响应。
         */
        NotFoundResponse: {
            /**
             * Code
             * @default 404
             */
            code: number;
            /** Message */
            message?: string;
            /** Data */
            data?: null;
        };
        /** PaginatedResponse[RoleResponse] */
        PaginatedResponse_RoleResponse_: {
            /**
             * Page
             * @description 页码。
             */
            page: number;
            /**
             * Pagesize
             * @description 每页条数。
             */
            pageSize: number;
            /**
             * Total
             * @description 总条数。
             */
            total: number;
            /**
             * Records
             * @description 记录列表。
             */
            records: components["schemas"]["RoleResponse"][];
        };
        /**
         * PermissionResponse
         * @description 统一权限响应。
         */
        PermissionResponse: {
            /**
             * Code
             * @default 403
             */
            code: number;
            /** Message */
            message?: string;
            /** Data */
            data?: null;
        };
        /** Response[PaginatedResponse[RoleResponse]] */
        Response_PaginatedResponse_RoleResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["PaginatedResponse_RoleResponse_"] | null;
        };
        /** Response[RoleResponse] */
        Response_RoleResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["RoleResponse"] | null;
        };
        /** Response[TokenResponse] */
        Response_TokenResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["TokenResponse"] | null;
        };
        /** Response[UserInfoResponse] */
        Response_UserInfoResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["UserInfoResponse"] | null;
        };
        /** Response[bool] */
        Response_bool_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: boolean | null;
        };
        /** Response[list[FastAPIRouterResponse]] */
        Response_list_FastAPIRouterResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: components["schemas"]["FastAPIRouterResponse"][] | null;
        };
        /** Response[list[RoleResponse]] */
        Response_list_RoleResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: components["schemas"]["RoleResponse"][] | null;
        };
        /** Response[str] */
        Response_str_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: string | null;
        };
        /**
         * RoleBatchBody
         * @description 批量角色操作数据结构。
         */
        RoleBatchBody: {
            /**
             * Ids
             * @description 项 id 列表。
             */
            ids: string[];
        };
        /**
         * RoleCreate
         * @description 创建角色数据结构。
         */
        RoleCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleResponse
         * @description 角色响应数据结构。
         */
        RoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleUpdate
         * @description 更新角色数据结构。
         */
        RoleUpdate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * ServerErrorResponse
         * @description 统一服务器错误响应。
         */
        ServerErrorResponse: {
            /**
             * Code
             * @default 500
             */
            code: number;
            /** Message */
            message?: string;
            /**
             * Data
             * @default Internal server error details.
             */
            data: string;
        };
        /**
         * TokenResponse
         * @description 令牌响应。
         */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * UserInfoResponse
         * @description 用户信息响应数据结构。
         */
        UserInfoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /**
             * Roles
             * @default []
             */
            roles: string[];
            /**
             * Buttons
             * @default []
             */
            buttons: string[];
        };
        /**
         * ValidationErrorResponse
         * @description 统一参数校验失败响应。
         */
        ValidationErrorResponse: {
            /**
             * Code
             * @default 422
             */
            code: number;
            /** Message */
            message?: string;
            /**
             * Data
             * @default Validation error details.
             */
            data: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_public_key_api_v1_auth_keys_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_str_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_token_refresh_post: {
        parameters: {
            query?: never;
            header: {
                "x-refresh-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_user_info_api_v1_auth_user_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserInfoResponse_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_router_api_v1_router_backend_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_FastAPIRouterResponse__"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_roles_api_v1_roles_get: {
        parameters: {
            query: {
                /** @description 当前页码。 */
                page: number;
                /** @description 每页条数。 */
                pageSize: number;
                keyword?: string;
                status?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_PaginatedResponse_RoleResponse__"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    batch_delete_role_api_v1_roles_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_my_roles_api_v1_roles_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    get_all_roles_api_v1_roles_all_get: {
        parameters: {
            query?: {
                keyword?: string;
                status?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Bad Request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationError"];
                };
            };
            /** @description Permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Unprocessable Entity. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Internal Server Error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerErrorResponse"];
                };
            };
        };
    };
}
