/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/keys/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Key
         * @description 得到用于 RSA 加密密码的公开密钥。
         */
        get: operations["get_public_key_api_v1_auth_keys_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录端点。
         *
         *     该端点验证用户的凭证，解密密码，需验证数据库，并在成功时返回访问令牌和刷新令牌。
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 登出当前用户。
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description 使用刷新令牌刷新用户的访问令牌。
         */
        post: operations["refresh_token_api_v1_auth_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description 检索当前的用户信息。
         *
         *     该端点在验证令牌和从数据库检索了完整记录后需出有详细信息。
         */
        get: operations["get_user_info_api_v1_auth_user_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/backend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Router
         * @description 该端点从数据库检索所有路由并在响应中返回。
         */
        get: operations["get_router_api_v1_router_backend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roles
         * @description 获取分页的角色列表。
         */
        get: operations["get_roles_api_v1_roles_get"];
        put?: never;
        /**
         * Create Role
         * @description 创建一个新角色。
         */
        post: operations["create_role_api_v1_roles_post"];
        /**
         * Batch Delete Role
         * @description 根据 ID 列表删除多个角色。
         */
        delete: operations["batch_delete_role_api_v1_roles_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Roles
         * @description 获取分配给当前用户的角色。
         */
        get: operations["get_my_roles_api_v1_roles_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Roles
         * @description 获取不带分页的完整角色列表。
         */
        get: operations["get_all_roles_api_v1_roles_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Role
         * @description 根据 ID 更新角色。
         */
        put: operations["update_role_api_v1_roles__role_id__put"];
        post?: never;
        /**
         * Delete Role
         * @description 根据 ID 删除单个角色。
         */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Menu List
         * @description 获取菜单列表（支持分页）
         */
        get: operations["get_menu_list_api_v1_manage_menus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Pages
         * @description 获取所有页面组件名称
         */
        get: operations["get_all_pages_api_v1_manage_pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Menu
         * @description 新增菜单。
         */
        post: operations["add_menu_api_v1_manage_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Menu
         * @description 更新菜单。
         */
        put: operations["update_menu_api_v1_manage_update_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Menu
         * @description 删除单个菜单。
         */
        delete: operations["delete_menu_api_v1_manage_delete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/batchDelete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Delete Menus
         * @description 批量删除菜单。
         */
        post: operations["batch_delete_menus_api_v1_manage_batchDelete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Button */
        Button: {
            /** Code */
            code: string;
            /** Desc */
            desc: string;
        };
        /**
         * FastAPIRouterResponse
         * @description 接口路由响应数据结构。
         */
        FastAPIRouterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Path */
            path: string;
            /** Methods */
            methods: string[];
            /**
             * Code
             * @description 角色接口权限编码。
             */
            readonly code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description 登录请求数据结构。
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * MenuBatchRequest
         * @description 批量操作菜单请求。
         */
        MenuBatchRequest: {
            /**
             * Ids
             * @description 菜单 ID 列表
             */
            ids: string[];
        };
        /**
         * MenuCreate
         * @description 创建菜单请求。
         */
        MenuCreate: {
            /**
             * Menuname
             * @description 菜单名称
             */
            menuName: string;
            /**
             * @description 菜单类型: 1-目录, 2-菜单
             * @default 1
             */
            menuType: components["schemas"]["MenuType"];
            /**
             * Order
             * @description 排序序号
             * @default 0
             */
            order: number;
            /**
             * Routename
             * @description 路由名称
             */
            routeName: string;
            /**
             * Routepath
             * @description 路由路径
             */
            routePath: string;
            /**
             * Component
             * @description 组件路径
             */
            component?: string | null;
            /**
             * Icon
             * @description 图标名称
             */
            icon?: string | null;
            /**
             * @description 图标类型
             * @default 1
             */
            iconType: components["schemas"]["MenuIconType"];
            /**
             * @description 状态
             * @default 1
             */
            status: components["schemas"]["Status"];
            /**
             * Hideinmenu
             * @description 是否隐藏
             * @default false
             */
            hideInMenu: boolean;
            /**
             * Parentid
             * @description 父级ID
             */
            parentId?: string | null;
            /**
             * I18Nkey
             * @description 国际化Key
             */
            i18NKey?: string | null;
            /**
             * Keepalive
             * @description 是否缓存
             * @default false
             */
            keepAlive: boolean;
            /**
             * Constant
             * @description 是否常量路由
             * @default false
             */
            constant: boolean;
            /**
             * Href
             * @description 外链
             */
            href?: string | null;
            /**
             * Multitab
             * @description 是否支持多页签
             * @default false
             */
            multiTab: boolean;
            /**
             * Fixedindexintab
             * @description 固定页签次序
             */
            fixedIndexInTab?: number | null;
            /**
             * Query
             * @description 路由参数
             * @default []
             */
            query: components["schemas"]["Query"][];
            /**
             * Buttons
             * @description 按钮权限
             * @default []
             */
            buttons: components["schemas"]["Button"][];
        };
        /**
         * MenuIconType
         * @enum {string}
         */
        MenuIconType: "1" | "2";
        /** MenuListResponse */
        MenuListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /**
             * Menuname
             * @description 菜单名称
             */
            menuName: string;
            /**
             * @description 菜单类型: 1-目录, 2-菜单
             * @default 1
             */
            menuType: components["schemas"]["MenuType"];
            /**
             * Order
             * @description 排序序号
             * @default 0
             */
            order: number;
            /**
             * Routename
             * @description 路由名称
             */
            routeName: string;
            /**
             * Routepath
             * @description 路由路径
             */
            routePath: string;
            /**
             * Component
             * @description 组件路径
             */
            component?: string | null;
            /**
             * Icon
             * @description 图标名称
             */
            icon?: string | null;
            /**
             * @description 图标类型
             * @default 1
             */
            iconType: components["schemas"]["MenuIconType"];
            /**
             * @description 状态
             * @default 1
             */
            status: components["schemas"]["Status"];
            /**
             * Hideinmenu
             * @description 是否隐藏
             * @default false
             */
            hideInMenu: boolean;
            /**
             * Parentid
             * @description 父级ID
             */
            parentId?: string | null;
            /**
             * I18Nkey
             * @description 国际化Key
             */
            i18NKey?: string | null;
            /**
             * Keepalive
             * @description 是否缓存
             * @default false
             */
            keepAlive: boolean;
            /**
             * Constant
             * @description 是否常量路由
             * @default false
             */
            constant: boolean;
            /**
             * Href
             * @description 外链
             */
            href?: string | null;
            /**
             * Multitab
             * @description 是否支持多页签
             * @default false
             */
            multiTab: boolean;
            /**
             * Fixedindexintab
             * @description 固定页签次序
             */
            fixedIndexInTab?: number | null;
            /**
             * Query
             * @description 路由参数
             * @default []
             */
            query: components["schemas"]["Query"][];
            /**
             * Buttons
             * @description 按钮权限
             * @default []
             */
            buttons: components["schemas"]["Button"][];
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["MenuListResponse"][];
        };
        /**
         * MenuResponse
         * @description 菜单响应数据结构。
         */
        MenuResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /**
             * Menuname
             * @description 菜单名称
             */
            menuName: string;
            /**
             * @description 菜单类型: 1-目录, 2-菜单
             * @default 1
             */
            menuType: components["schemas"]["MenuType"];
            /**
             * Order
             * @description 排序序号
             * @default 0
             */
            order: number;
            /**
             * Routename
             * @description 路由名称
             */
            routeName: string;
            /**
             * Routepath
             * @description 路由路径
             */
            routePath: string;
            /**
             * Component
             * @description 组件路径
             */
            component?: string | null;
            /**
             * Icon
             * @description 图标名称
             */
            icon?: string | null;
            /**
             * @description 图标类型
             * @default 1
             */
            iconType: components["schemas"]["MenuIconType"];
            /**
             * @description 状态
             * @default 1
             */
            status: components["schemas"]["Status"];
            /**
             * Hideinmenu
             * @description 是否隐藏
             * @default false
             */
            hideInMenu: boolean;
            /**
             * Parentid
             * @description 父级ID
             */
            parentId?: string | null;
            /**
             * I18Nkey
             * @description 国际化Key
             */
            i18NKey?: string | null;
            /**
             * Keepalive
             * @description 是否缓存
             * @default false
             */
            keepAlive: boolean;
            /**
             * Constant
             * @description 是否常量路由
             * @default false
             */
            constant: boolean;
            /**
             * Href
             * @description 外链
             */
            href?: string | null;
            /**
             * Multitab
             * @description 是否支持多页签
             * @default false
             */
            multiTab: boolean;
            /**
             * Fixedindexintab
             * @description 固定页签次序
             */
            fixedIndexInTab?: number | null;
            /**
             * Query
             * @description 路由参数
             * @default []
             */
            query: components["schemas"]["Query"][];
            /**
             * Buttons
             * @description 按钮权限
             * @default []
             */
            buttons: components["schemas"]["Button"][];
        };
        /**
         * MenuType
         * @enum {string}
         */
        MenuType: "1" | "2";
        /**
         * MenuUpdate
         * @description 更新菜单请求。
         */
        MenuUpdate: {
            /**
             * Menuname
             * @description 菜单名称
             */
            menuName: string;
            /**
             * @description 菜单类型: 1-目录, 2-菜单
             * @default 1
             */
            menuType: components["schemas"]["MenuType"];
            /**
             * Order
             * @description 排序序号
             * @default 0
             */
            order: number;
            /**
             * Routename
             * @description 路由名称
             */
            routeName: string;
            /**
             * Routepath
             * @description 路由路径
             */
            routePath: string;
            /**
             * Component
             * @description 组件路径
             */
            component?: string | null;
            /**
             * Icon
             * @description 图标名称
             */
            icon?: string | null;
            /**
             * @description 图标类型
             * @default 1
             */
            iconType: components["schemas"]["MenuIconType"];
            /**
             * @description 状态
             * @default 1
             */
            status: components["schemas"]["Status"];
            /**
             * Hideinmenu
             * @description 是否隐藏
             * @default false
             */
            hideInMenu: boolean;
            /**
             * Parentid
             * @description 父级ID
             */
            parentId?: string | null;
            /**
             * I18Nkey
             * @description 国际化Key
             */
            i18NKey?: string | null;
            /**
             * Keepalive
             * @description 是否缓存
             * @default false
             */
            keepAlive: boolean;
            /**
             * Constant
             * @description 是否常量路由
             * @default false
             */
            constant: boolean;
            /**
             * Href
             * @description 外链
             */
            href?: string | null;
            /**
             * Multitab
             * @description 是否支持多页签
             * @default false
             */
            multiTab: boolean;
            /**
             * Fixedindexintab
             * @description 固定页签次序
             */
            fixedIndexInTab?: number | null;
            /**
             * Query
             * @description 路由参数
             * @default []
             */
            query: components["schemas"]["Query"][];
            /**
             * Buttons
             * @description 按钮权限
             * @default []
             */
            buttons: components["schemas"]["Button"][];
        };
        /** PaginatedResponse[MenuListResponse] */
        PaginatedResponse_MenuListResponse_: {
            /**
             * Page
             * @description 页码。
             */
            page: number;
            /**
             * Pagesize
             * @description 每页条数。
             */
            pageSize: number;
            /**
             * Total
             * @description 总条数。
             */
            total: number;
            /**
             * Records
             * @description 记录列表。
             */
            records: components["schemas"]["MenuListResponse"][];
        };
        /** PaginatedResponse[RoleResponse] */
        PaginatedResponse_RoleResponse_: {
            /**
             * Page
             * @description 页码。
             */
            page: number;
            /**
             * Pagesize
             * @description 每页条数。
             */
            pageSize: number;
            /**
             * Total
             * @description 总条数。
             */
            total: number;
            /**
             * Records
             * @description 记录列表。
             */
            records: components["schemas"]["RoleResponse"][];
        };
        /** Query */
        Query: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** Response[MenuResponse] */
        Response_MenuResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["MenuResponse"] | null;
        };
        /** Response[PaginatedResponse[MenuListResponse]] */
        Response_PaginatedResponse_MenuListResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["PaginatedResponse_MenuListResponse_"] | null;
        };
        /** Response[PaginatedResponse[RoleResponse]] */
        Response_PaginatedResponse_RoleResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["PaginatedResponse_RoleResponse_"] | null;
        };
        /** Response[RoleResponse] */
        Response_RoleResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["RoleResponse"] | null;
        };
        /** Response[TokenResponse] */
        Response_TokenResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["TokenResponse"] | null;
        };
        /** Response[UserInfoResponse] */
        Response_UserInfoResponse_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /** @description 响应数据。 */
            data?: components["schemas"]["UserInfoResponse"] | null;
        };
        /** Response[bool] */
        Response_bool_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: boolean | null;
        };
        /** Response[list[FastAPIRouterResponse]] */
        Response_list_FastAPIRouterResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: components["schemas"]["FastAPIRouterResponse"][] | null;
        };
        /** Response[list[RoleResponse]] */
        Response_list_RoleResponse__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: components["schemas"]["RoleResponse"][] | null;
        };
        /** Response[list[str]] */
        Response_list_str__: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: string[] | null;
        };
        /** Response[str] */
        Response_str_: {
            /**
             * Code
             * @description 状态码。
             * @default 0
             */
            code: number;
            /**
             * Message
             * @description 响应消息。
             */
            message?: string;
            /**
             * Data
             * @description 响应数据。
             */
            data?: string | null;
        };
        /**
         * RoleBatchBody
         * @description 批量角色操作数据结构。
         */
        RoleBatchBody: {
            /**
             * Ids
             * @description 项 id 列表。
             */
            ids: string[];
        };
        /**
         * RoleCreate
         * @description 创建角色数据结构。
         */
        RoleCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /** @default 1 */
            status: components["schemas"]["Status"];
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleResponse
         * @description 角色响应数据结构。
         */
        RoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /** @default 1 */
            status: components["schemas"]["Status"];
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * RoleUpdate
         * @description 更新角色数据结构。
         */
        RoleUpdate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
            /** @default 1 */
            status: components["schemas"]["Status"];
            /**
             * Interfacepermissions
             * @default []
             */
            interfacePermissions: string[];
            /**
             * Buttonpermissions
             * @default []
             */
            buttonPermissions: string[];
            /**
             * Routerpermissions
             * @default []
             */
            routerPermissions: string[];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "1" | "2";
        /**
         * TokenResponse
         * @description 令牌响应。
         */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * UserInfoResponse
         * @description 用户信息响应数据结构。
         */
        UserInfoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createtime
             * @example 2024-07-31 16:07:34
             */
            createTime: string;
            /**
             * Updatetime
             * @example 2024-07-31 16:07:34
             */
            updateTime: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /**
             * Roles
             * @default []
             */
            roles: string[];
            /**
             * Buttons
             * @default []
             */
            buttons: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_public_key_api_v1_auth_keys_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_str_"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_token_refresh_post: {
        parameters: {
            query?: never;
            header: {
                "x-refresh-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_info_api_v1_auth_user_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_UserInfoResponse_"];
                };
            };
        };
    };
    get_router_api_v1_router_backend_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_FastAPIRouterResponse__"];
                };
            };
        };
    };
    get_roles_api_v1_roles_get: {
        parameters: {
            query?: {
                /** @description 当前页码。 */
                page?: number;
                /** @description 每页条数。 */
                pageSize?: number;
                keyword?: string;
                status?: components["schemas"]["Status"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_PaginatedResponse_RoleResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_role_api_v1_roles_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_roles_api_v1_roles_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
        };
    };
    get_all_roles_api_v1_roles_all_get: {
        parameters: {
            query?: {
                keyword?: string;
                status?: components["schemas"]["Status"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_RoleResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_RoleResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_list_api_v1_manage_menus_get: {
        parameters: {
            query?: {
                /** @description 当前页码。 */
                page?: number;
                /** @description 每页条数。 */
                pageSize?: number;
                keyword?: string;
                status?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_PaginatedResponse_MenuListResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_pages_api_v1_manage_pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_list_str__"];
                };
            };
        };
    };
    add_menu_api_v1_manage_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_menu_api_v1_manage_update_put: {
        parameters: {
            query: {
                menu_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_MenuResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_menu_api_v1_manage_delete_delete: {
        parameters: {
            query: {
                menu_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_menus_api_v1_manage_batchDelete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_bool_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
