"""e.g. add user table

Revision ID: c69e3fdeb2c5
Revises: 
Create Date: 2026-08-21 16:49:34.630157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c69e3fdeb2c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('monitoring',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
