"""init

Revision ID: f41a3a13fa0a
Revises: 
Create Date: 2026-09-02 16:27:53.438470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f41a3a13fa0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('monitoring',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_api_metrics_hourly',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('time_bucket', sa.DateTime(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('avg_ms', sa.Float(), nullable=False),
    sa.Column('p95_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_metrics_time', 'monitoring_api_metrics_hourly', ['time_bucket'], unique=False)
    op.create_index('idx_api_metrics_unique', 'monitoring_api_metrics_hourly', ['time_bucket', 'method', 'path'], unique=True)
    op.create_index(op.f('ix_monitoring_api_metrics_hourly_created_by'), 'monitoring_api_metrics_hourly', ['created_by'], unique=False)
    op.create_index(op.f('ix_monitoring_api_metrics_hourly_id'), 'monitoring_api_metrics_hourly', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_api_metrics_hourly_id'), table_name='monitoring_api_metrics_hourly')
    op.drop_index(op.f('ix_monitoring_api_metrics_hourly_created_by'), table_name='monitoring_api_metrics_hourly')
    op.drop_index('idx_api_metrics_unique', table_name='monitoring_api_metrics_hourly')
    op.drop_index('idx_api_metrics_time', table_name='monitoring_api_metrics_hourly')
    op.drop_table('monitoring_api_metrics_hourly')
    # ### end Alembic commands ###
