"""init

Revision ID: 0b7ddc6e48bb
Revises: 
Create Date: 2026-09-02 16:27:47.270177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b7ddc6e48bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('department',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept_departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON', 'OFF', 'PENDING', name='status'), nullable=False),
    sa.Column('leader_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_dept_departments_created_by'), 'dept_departments', ['created_by'], unique=False)
    op.create_index(op.f('ix_dept_departments_id'), 'dept_departments', ['id'], unique=False)
    op.create_index(op.f('ix_dept_departments_parent_id'), 'dept_departments', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dept_departments_parent_id'), table_name='dept_departments')
    op.drop_index(op.f('ix_dept_departments_id'), table_name='dept_departments')
    op.drop_index(op.f('ix_dept_departments_created_by'), table_name='dept_departments')
    op.drop_table('dept_departments')
    # ### end Alembic commands ###
