"""e.g. add user table

Revision ID: 727c54e0ffb3
Revises: 8314da32f892
Create Date: 2026-08-27 17:43:57.767181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '727c54e0ffb3'
down_revision: Union[str, None] = '8314da32f892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE "status" ADD VALUE IF NOT EXISTS \'PENDING\'')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # PostgreSQL enum value 'PENDING' is not removed automatically
    # ### end Alembic commands ###
