"""e.g. add user table

Revision ID: 8314da32f892
Revises: 
Create Date: 2026-08-27 17:01:48.249126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8314da32f892'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('department',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
