"""e.g. add user table

Revision ID: 127fdf7dd3be
Revises: 
Create Date: 2026-08-27 17:01:50.601221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '127fdf7dd3be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('permission',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
