"""init

Revision ID: f45820b469a9
Revises: 
Create Date: 2026-09-02 16:27:56.791937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f45820b469a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('permission',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_data_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_data_policies_created_by'), 'permission_data_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_data_policies_id'), 'permission_data_policies', ['id'], unique=False)
    op.create_table('permission_field_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_field_policies_created_by'), 'permission_field_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_field_policies_id'), 'permission_field_policies', ['id'], unique=False)
    op.create_table('permission_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.Column('interface_permissions', sa.JSON(), nullable=True),
    sa.Column('button_permissions', sa.JSON(), nullable=True),
    sa.Column('router_permissions', sa.JSON(), nullable=True),
    sa.Column('data_policy_ids', sa.JSON(), nullable=True),
    sa.Column('field_policy_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_roles_created_by'), 'permission_roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_roles_id'), 'permission_roles', ['id'], unique=False)
    op.create_table('permission_routers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_routers_created_by'), 'permission_routers', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_routers_id'), 'permission_routers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_routers_id'), table_name='permission_routers')
    op.drop_index(op.f('ix_permission_routers_created_by'), table_name='permission_routers')
    op.drop_table('permission_routers')
    op.drop_index(op.f('ix_permission_roles_id'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_created_by'), table_name='permission_roles')
    op.drop_table('permission_roles')
    op.drop_index(op.f('ix_permission_field_policies_id'), table_name='permission_field_policies')
    op.drop_index(op.f('ix_permission_field_policies_created_by'), table_name='permission_field_policies')
    op.drop_table('permission_field_policies')
    op.drop_index(op.f('ix_permission_data_policies_id'), table_name='permission_data_policies')
    op.drop_index(op.f('ix_permission_data_policies_created_by'), table_name='permission_data_policies')
    op.drop_table('permission_data_policies')
    # ### end Alembic commands ###
