/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "manage_audit-dict": () => import("@/views/manage/audit-dict/index.vue"),
  "manage_data-rule": () => import("@/views/manage/data-rule/index.vue"),
  manage_department: () => import("@/views/manage/department/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  monitoring_api: () => import("@/views/monitoring/api/index.vue"),
  monitoring_plugin: () => import("@/views/monitoring/plugin/index.vue"),
  queue_dashboard: () => import("@/views/queue/dashboard/index.vue"),
  queue_schedule: () => import("@/views/queue/schedule/index.vue"),
  queue_task: () => import("@/views/queue/task/index.vue"),
  script: () => import("@/views/script/index.vue"),
  socketio_chat: () => import("@/views/socketio/chat/index.vue"),
  socketio_debug: () => import("@/views/socketio/debug/index.vue"),
  socketio_instrument: () => import("@/views/socketio/instrument/index.vue"),
};
