/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

/* prettier-ignore */
export const generatedRoutes: GeneratedRoute[] = [{
  name: '403',
  path: '/403',
  component: 'layout.blank$view.403',
  meta: {
    title: '403',
    i18nKey: 'route.403',
    constant: true,
    hideInMenu: true
  }
}, {
  name: '404',
  path: '/404',
  component: 'layout.blank$view.404',
  meta: {
    title: '404',
    i18nKey: 'route.404',
    constant: true,
    hideInMenu: true
  }
}, {
  name: '500',
  path: '/500',
  component: 'layout.blank$view.500',
  meta: {
    title: '500',
    i18nKey: 'route.500',
    constant: true,
    hideInMenu: true
  }
}, {
  name: 'home',
  path: '/home',
  component: 'layout.base$view.home',
  meta: {
    title: 'home',
    i18nKey: 'route.home',
    icon: 'mdi:monitor-dashboard',
    order: 1
  }
}, {
  name: 'iframe-page',
  path: '/iframe-page/:url',
  component: 'layout.base$view.iframe-page',
  props: true,
  meta: {
    title: 'iframe-page',
    i18nKey: 'route.iframe-page',
    constant: true,
    hideInMenu: true,
    keepAlive: true
  }
}, {
  name: 'login',
  path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
  component: 'layout.blank$view.login',
  props: true,
  meta: {
    title: 'login',
    i18nKey: 'route.login',
    constant: true,
    hideInMenu: true
  }
}, {
  name: 'manage',
  path: '/manage',
  component: 'layout.base',
  meta: {
    title: 'manage',
    order: 9,
    icon: 'tabler:settings-spark',
    i18nKey: 'route.manage'
  },
  children: [{
    name: 'manage_audit-dict',
    path: '/manage/audit-dict',
    component: 'view.manage_audit-dict',
    meta: {
      title: 'manage_audit-dict',
      i18nKey: 'route.manage_audit-dict'
    }
  }, {
    name: 'manage_data-rule',
    path: '/manage/data-rule',
    component: 'view.manage_data-rule',
    meta: {
      title: 'manage_data-rule',
      i18nKey: 'route.manage_data-rule'
    }
  }, {
    name: 'manage_department',
    path: '/manage/department',
    component: 'view.manage_department',
    meta: {
      title: 'manage_department',
      i18nKey: 'route.manage_department'
    }
  }, {
    name: 'manage_menu',
    path: '/manage/menu',
    component: 'view.manage_menu',
    meta: {
      title: 'manage_menu',
      i18nKey: 'route.manage_menu',
      icon: 'material-symbols:route'
    }
  }, {
    name: 'manage_role',
    path: '/manage/role',
    component: 'view.manage_role',
    meta: {
      title: 'manage_role',
      i18nKey: 'route.manage_role',
      icon: 'carbon:user-role'
    }
  }, {
    name: 'manage_user',
    path: '/manage/user',
    component: 'view.manage_user',
    meta: {
      icon: 'ic:round-manage-accounts',
      title: 'manage_user',
      i18nKey: 'route.manage_user'
    }
  }, {
    name: 'manage_user-detail',
    path: '/manage/user-detail/:id',
    component: 'view.manage_user-detail',
    props: true,
    meta: {
      title: 'manage_user-detail',
      hideInMenu: true,
      i18nKey: 'route.manage_user-detail'
    }
  }]
}, {
  name: 'monitoring',
  path: '/monitoring',
  component: 'layout.base',
  meta: {
    title: 'monitoring',
    i18nKey: 'route.monitoring'
  },
  children: [{
    name: 'monitoring_api',
    path: '/monitoring/api',
    component: 'view.monitoring_api',
    meta: {
      title: 'monitoring_api',
      i18nKey: 'route.monitoring_api'
    }
  }, {
    name: 'monitoring_plugin',
    path: '/monitoring/plugin',
    component: 'view.monitoring_plugin',
    meta: {
      title: 'monitoring_plugin',
      i18nKey: 'route.monitoring_plugin'
    }
  }]
}, {
  name: 'queue',
  path: '/queue',
  component: 'layout.base',
  meta: {
    title: 'queue',
    i18nKey: 'route.queue',
    icon: 'material-symbols:queue-play-next-outline',
    order: 7
  },
  children: [{
    name: 'queue_dashboard',
    path: '/queue/dashboard',
    component: 'view.queue_dashboard',
    meta: {
      title: 'queue_dashboard',
      i18nKey: 'route.queue_dashboard',
      icon: 'material-symbols:dashboard-outline-rounded'
    }
  }, {
    name: 'queue_schedule',
    path: '/queue/schedule',
    component: 'view.queue_schedule',
    meta: {
      title: 'queue_schedule',
      i18nKey: 'route.queue_schedule',
      icon: 'material-symbols:alarm-smart-wake-outline'
    }
  }, {
    name: 'queue_task',
    path: '/queue/task',
    component: 'view.queue_task',
    meta: {
      title: 'queue_task',
      i18nKey: 'route.queue_task',
      icon: 'material-symbols:history-2'
    }
  }]
}, {
  name: 'script',
  path: '/script',
  component: 'layout.base$view.script',
  meta: {
    title: 'script',
    i18nKey: 'route.script',
    icon: 'streamline-ultimate:programming-browser-1-bold',
    order: 12
  }
}, {
  name: 'socketio',
  path: '/socketio',
  component: 'layout.base',
  meta: {
    icon: 'ri:message-ai-3-line',
    title: 'socketio',
    i18nKey: 'route.socketio',
    order: 6
  },
  children: [{
    name: 'socketio_chat',
    path: '/socketio/chat',
    component: 'view.socketio_chat',
    meta: {
      title: 'socketio_chat',
      icon: 'fluent:chat-multiple-24-regular',
      i18nKey: 'route.socketio_chat',
      order: 5
    }
  }, {
    name: 'socketio_debug',
    path: '/socketio/debug',
    component: 'view.socketio_debug',
    meta: {
      title: 'socketio_debug',
      icon: 'codicon:debug-all',
      order: 4,
      i18nKey: 'route.socketio_debug'
    }
  }, {
    name: 'socketio_instrument',
    path: '/socketio/instrument',
    component: 'view.socketio_instrument',
    meta: {
      title: 'socketio_instrument',
      icon: 'stash:dashboard',
      order: 3,
      i18nKey: 'route.socketio_instrument'
    }
  }]
}];
