"""init

Revision ID: 822be375d033
Revises: 
Create Date: 2026-09-02 16:28:00.278151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '822be375d033'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('schedule',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_crontab_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('minute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month_of_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_crontab_schedules_created_by'), 'schedule_crontab_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_crontab_schedules_id'), 'schedule_crontab_schedules', ['id'], unique=False)
    op.create_table('schedule_interval_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('every', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('WEEKS', 'DAYS', 'HOURS', 'MINUTES', 'SECONDS', 'MILLISECONDS', 'MICROSECONDS', name='period'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_interval_schedules_created_by'), 'schedule_interval_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_interval_schedules_id'), 'schedule_interval_schedules', ['id'], unique=False)
    op.create_table('schedule_periodic_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_type', sa.Enum('INTERVAL', 'CRONTAB', 'SOLAR', name='tasktype'), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_periodic_tasks_created_by'), 'schedule_periodic_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_periodic_tasks_id'), 'schedule_periodic_tasks', ['id'], unique=False)
    op.create_table('schedule_solar_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('event', sa.Enum('DAWN_ASTRONOMICAL', 'DAWN_NAUTICAL', 'DAWN_CIVIL', 'SUNRISE', 'SOLAR_NOON', 'SUNSET', 'DUSK_CIVIL', 'DUSK_NAUTICAL', 'DUSK_ASTRONOMICAL', name='solarevent'), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_solar_schedules_created_by'), 'schedule_solar_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_solar_schedules_id'), 'schedule_solar_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_solar_schedules_id'), table_name='schedule_solar_schedules')
    op.drop_index(op.f('ix_schedule_solar_schedules_created_by'), table_name='schedule_solar_schedules')
    op.drop_table('schedule_solar_schedules')
    op.drop_index(op.f('ix_schedule_periodic_tasks_id'), table_name='schedule_periodic_tasks')
    op.drop_index(op.f('ix_schedule_periodic_tasks_created_by'), table_name='schedule_periodic_tasks')
    op.drop_table('schedule_periodic_tasks')
    op.drop_index(op.f('ix_schedule_interval_schedules_id'), table_name='schedule_interval_schedules')
    op.drop_index(op.f('ix_schedule_interval_schedules_created_by'), table_name='schedule_interval_schedules')
    op.drop_table('schedule_interval_schedules')
    op.drop_index(op.f('ix_schedule_crontab_schedules_id'), table_name='schedule_crontab_schedules')
    op.drop_index(op.f('ix_schedule_crontab_schedules_created_by'), table_name='schedule_crontab_schedules')
    op.drop_table('schedule_crontab_schedules')
    # ### end Alembic commands ###
