"""init

Revision ID: b4efa9f81f0d
Revises: 
Create Date: 2026-09-02 16:28:12.656516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4efa9f81f0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('worker',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_task_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'), nullable=False),
    sa.Column('worker_hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_task_results_created_by'), 'worker_task_results', ['created_by'], unique=False)
    op.create_index(op.f('ix_worker_task_results_id'), 'worker_task_results', ['id'], unique=False)
    op.create_index(op.f('ix_worker_task_results_task_id'), 'worker_task_results', ['task_id'], unique=True)
    op.create_index(op.f('ix_worker_task_results_task_name'), 'worker_task_results', ['task_name'], unique=False)
    op.create_index(op.f('ix_worker_task_results_worker_hostname'), 'worker_task_results', ['worker_hostname'], unique=False)
    op.create_table('worker_workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='workerstatus'), nullable=False),
    sa.Column('active_queues', sa.JSON(), nullable=True),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('active_task_count', sa.Integer(), nullable=False),
    sa.Column('load_average', sa.JSON(), nullable=True),
    sa.Column('software_info', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_workers_created_by'), 'worker_workers', ['created_by'], unique=False)
    op.create_index(op.f('ix_worker_workers_hostname'), 'worker_workers', ['hostname'], unique=True)
    op.create_index(op.f('ix_worker_workers_id'), 'worker_workers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_workers_id'), table_name='worker_workers')
    op.drop_index(op.f('ix_worker_workers_hostname'), table_name='worker_workers')
    op.drop_index(op.f('ix_worker_workers_created_by'), table_name='worker_workers')
    op.drop_table('worker_workers')
    op.drop_index(op.f('ix_worker_task_results_worker_hostname'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_task_name'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_task_id'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_id'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_created_by'), table_name='worker_task_results')
    op.drop_table('worker_task_results')
    # ### end Alembic commands ###
