"""e.g. add user table

Revision ID: 826038026163
Revises: 
Create Date: 2026-08-21 16:49:32.334446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '826038026163'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('script',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept_departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.Column('leader_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_dept_departments_created_by'), 'dept_departments', ['created_by'], unique=False)
    op.create_index(op.f('ix_dept_departments_id'), 'dept_departments', ['id'], unique=False)
    op.create_index(op.f('ix_dept_departments_parent_id'), 'dept_departments', ['parent_id'], unique=False)
    op.create_table('menu_menus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('menu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menu_type', sa.Enum('DIRECTORY', 'MENU', name='menutype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('route_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon_type', sa.Enum('ICONIFY', 'LOCAL', name='menuicontype'), nullable=False),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.Column('hide_in_menu', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('i18n_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keep_alive', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('multi_tab', sa.Boolean(), nullable=False),
    sa.Column('fixed_index_in_tab', sa.Integer(), nullable=True),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('interfaces', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_menus_created_by'), 'menu_menus', ['created_by'], unique=False)
    op.create_index(op.f('ix_menu_menus_id'), 'menu_menus', ['id'], unique=False)
    op.create_index(op.f('ix_menu_menus_route_name'), 'menu_menus', ['route_name'], unique=True)
    op.create_table('monitoring_api_metrics_hourly',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('time_bucket', sa.DateTime(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('avg_ms', sa.Float(), nullable=False),
    sa.Column('p95_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_metrics_time', 'monitoring_api_metrics_hourly', ['time_bucket'], unique=False)
    op.create_index('idx_api_metrics_unique', 'monitoring_api_metrics_hourly', ['time_bucket', 'method', 'path'], unique=True)
    op.create_index(op.f('ix_monitoring_api_metrics_hourly_created_by'), 'monitoring_api_metrics_hourly', ['created_by'], unique=False)
    op.create_index(op.f('ix_monitoring_api_metrics_hourly_id'), 'monitoring_api_metrics_hourly', ['id'], unique=False)
    op.create_table('permission_data_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_data_policies_created_by'), 'permission_data_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_data_policies_id'), 'permission_data_policies', ['id'], unique=False)
    op.create_table('permission_field_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_field_policies_created_by'), 'permission_field_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_field_policies_id'), 'permission_field_policies', ['id'], unique=False)
    op.create_table('permission_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.Column('interface_permissions', sa.JSON(), nullable=True),
    sa.Column('button_permissions', sa.JSON(), nullable=True),
    sa.Column('router_permissions', sa.JSON(), nullable=True),
    sa.Column('data_policy_ids', sa.JSON(), nullable=True),
    sa.Column('field_policy_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_roles_created_by'), 'permission_roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_roles_id'), 'permission_roles', ['id'], unique=False)
    op.create_table('permission_routers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_routers_created_by'), 'permission_routers', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_routers_id'), 'permission_routers', ['id'], unique=False)
    op.create_table('schedule_crontab_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('minute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month_of_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_crontab_schedules_created_by'), 'schedule_crontab_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_crontab_schedules_id'), 'schedule_crontab_schedules', ['id'], unique=False)
    op.create_table('schedule_interval_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('every', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('WEEKS', 'DAYS', 'HOURS', 'MINUTES', 'SECONDS', 'MILLISECONDS', 'MICROSECONDS', name='period'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_interval_schedules_created_by'), 'schedule_interval_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_interval_schedules_id'), 'schedule_interval_schedules', ['id'], unique=False)
    op.create_table('schedule_periodic_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_type', sa.Enum('INTERVAL', 'CRONTAB', 'SOLAR', name='tasktype'), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_periodic_tasks_created_by'), 'schedule_periodic_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_periodic_tasks_id'), 'schedule_periodic_tasks', ['id'], unique=False)
    op.create_table('schedule_solar_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('event', sa.Enum('DAWN_ASTRONOMICAL', 'DAWN_NAUTICAL', 'DAWN_CIVIL', 'SUNRISE', 'SOLAR_NOON', 'SUNSET', 'DUSK_CIVIL', 'DUSK_NAUTICAL', 'DUSK_ASTRONOMICAL', name='solarevent'), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_solar_schedules_created_by'), 'schedule_solar_schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_solar_schedules_id'), 'schedule_solar_schedules', ['id'], unique=False)
    op.create_table('script_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_executions_created_by'), 'script_executions', ['created_by'], unique=False)
    op.create_index(op.f('ix_script_executions_executor_id'), 'script_executions', ['executor_id'], unique=False)
    op.create_index(op.f('ix_script_executions_id'), 'script_executions', ['id'], unique=False)
    op.create_index(op.f('ix_script_executions_script_id'), 'script_executions', ['script_id'], unique=False)
    op.create_table('script_scripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_script_scripts_created_by'), 'script_scripts', ['created_by'], unique=False)
    op.create_index(op.f('ix_script_scripts_id'), 'script_scripts', ['id'], unique=False)
    op.create_table('system_activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('source_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_activity_logs_created_by'), 'system_activity_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_activity_logs_event_type'), 'system_activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_activity_logs_id'), 'system_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_activity_logs_user_id'), 'system_activity_logs', ['user_id'], unique=False)
    op.create_table('system_audit_dictionaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('label_zh', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label_en', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_audit_dict_key_category')
    )
    op.create_index(op.f('ix_system_audit_dictionaries_category'), 'system_audit_dictionaries', ['category'], unique=False)
    op.create_index(op.f('ix_system_audit_dictionaries_created_by'), 'system_audit_dictionaries', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_audit_dictionaries_id'), 'system_audit_dictionaries', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_dictionaries_key'), 'system_audit_dictionaries', ['key'], unique=False)
    op.create_table('user_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('status', sa.Enum('ON', 'OFF', name='status'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_users_created_by'), 'user_users', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_users_department_id'), 'user_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_users_id'), 'user_users', ['id'], unique=False)
    op.create_table('worker_task_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'), nullable=False),
    sa.Column('worker_hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_task_results_created_by'), 'worker_task_results', ['created_by'], unique=False)
    op.create_index(op.f('ix_worker_task_results_id'), 'worker_task_results', ['id'], unique=False)
    op.create_index(op.f('ix_worker_task_results_task_id'), 'worker_task_results', ['task_id'], unique=True)
    op.create_index(op.f('ix_worker_task_results_task_name'), 'worker_task_results', ['task_name'], unique=False)
    op.create_index(op.f('ix_worker_task_results_worker_hostname'), 'worker_task_results', ['worker_hostname'], unique=False)
    op.create_table('worker_workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='workerstatus'), nullable=False),
    sa.Column('active_queues', sa.JSON(), nullable=True),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('active_task_count', sa.Integer(), nullable=False),
    sa.Column('load_average', sa.JSON(), nullable=True),
    sa.Column('software_info', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_workers_created_by'), 'worker_workers', ['created_by'], unique=False)
    op.create_index(op.f('ix_worker_workers_hostname'), 'worker_workers', ['hostname'], unique=True)
    op.create_index(op.f('ix_worker_workers_id'), 'worker_workers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_workers_id'), table_name='worker_workers')
    op.drop_index(op.f('ix_worker_workers_hostname'), table_name='worker_workers')
    op.drop_index(op.f('ix_worker_workers_created_by'), table_name='worker_workers')
    op.drop_table('worker_workers')
    op.drop_index(op.f('ix_worker_task_results_worker_hostname'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_task_name'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_task_id'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_id'), table_name='worker_task_results')
    op.drop_index(op.f('ix_worker_task_results_created_by'), table_name='worker_task_results')
    op.drop_table('worker_task_results')
    op.drop_index(op.f('ix_user_users_id'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_department_id'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_created_by'), table_name='user_users')
    op.drop_table('user_users')
    op.drop_index(op.f('ix_system_audit_dictionaries_key'), table_name='system_audit_dictionaries')
    op.drop_index(op.f('ix_system_audit_dictionaries_id'), table_name='system_audit_dictionaries')
    op.drop_index(op.f('ix_system_audit_dictionaries_created_by'), table_name='system_audit_dictionaries')
    op.drop_index(op.f('ix_system_audit_dictionaries_category'), table_name='system_audit_dictionaries')
    op.drop_table('system_audit_dictionaries')
    op.drop_index(op.f('ix_system_activity_logs_user_id'), table_name='system_activity_logs')
    op.drop_index(op.f('ix_system_activity_logs_id'), table_name='system_activity_logs')
    op.drop_index(op.f('ix_system_activity_logs_event_type'), table_name='system_activity_logs')
    op.drop_index(op.f('ix_system_activity_logs_created_by'), table_name='system_activity_logs')
    op.drop_table('system_activity_logs')
    op.drop_index(op.f('ix_script_scripts_id'), table_name='script_scripts')
    op.drop_index(op.f('ix_script_scripts_created_by'), table_name='script_scripts')
    op.drop_table('script_scripts')
    op.drop_index(op.f('ix_script_executions_script_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_executor_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_created_by'), table_name='script_executions')
    op.drop_table('script_executions')
    op.drop_index(op.f('ix_schedule_solar_schedules_id'), table_name='schedule_solar_schedules')
    op.drop_index(op.f('ix_schedule_solar_schedules_created_by'), table_name='schedule_solar_schedules')
    op.drop_table('schedule_solar_schedules')
    op.drop_index(op.f('ix_schedule_periodic_tasks_id'), table_name='schedule_periodic_tasks')
    op.drop_index(op.f('ix_schedule_periodic_tasks_created_by'), table_name='schedule_periodic_tasks')
    op.drop_table('schedule_periodic_tasks')
    op.drop_index(op.f('ix_schedule_interval_schedules_id'), table_name='schedule_interval_schedules')
    op.drop_index(op.f('ix_schedule_interval_schedules_created_by'), table_name='schedule_interval_schedules')
    op.drop_table('schedule_interval_schedules')
    op.drop_index(op.f('ix_schedule_crontab_schedules_id'), table_name='schedule_crontab_schedules')
    op.drop_index(op.f('ix_schedule_crontab_schedules_created_by'), table_name='schedule_crontab_schedules')
    op.drop_table('schedule_crontab_schedules')
    op.drop_index(op.f('ix_permission_routers_id'), table_name='permission_routers')
    op.drop_index(op.f('ix_permission_routers_created_by'), table_name='permission_routers')
    op.drop_table('permission_routers')
    op.drop_index(op.f('ix_permission_roles_id'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_created_by'), table_name='permission_roles')
    op.drop_table('permission_roles')
    op.drop_index(op.f('ix_permission_field_policies_id'), table_name='permission_field_policies')
    op.drop_index(op.f('ix_permission_field_policies_created_by'), table_name='permission_field_policies')
    op.drop_table('permission_field_policies')
    op.drop_index(op.f('ix_permission_data_policies_id'), table_name='permission_data_policies')
    op.drop_index(op.f('ix_permission_data_policies_created_by'), table_name='permission_data_policies')
    op.drop_table('permission_data_policies')
    op.drop_index(op.f('ix_monitoring_api_metrics_hourly_id'), table_name='monitoring_api_metrics_hourly')
    op.drop_index(op.f('ix_monitoring_api_metrics_hourly_created_by'), table_name='monitoring_api_metrics_hourly')
    op.drop_index('idx_api_metrics_unique', table_name='monitoring_api_metrics_hourly')
    op.drop_index('idx_api_metrics_time', table_name='monitoring_api_metrics_hourly')
    op.drop_table('monitoring_api_metrics_hourly')
    op.drop_index(op.f('ix_menu_menus_route_name'), table_name='menu_menus')
    op.drop_index(op.f('ix_menu_menus_id'), table_name='menu_menus')
    op.drop_index(op.f('ix_menu_menus_created_by'), table_name='menu_menus')
    op.drop_table('menu_menus')
    op.drop_index(op.f('ix_dept_departments_parent_id'), table_name='dept_departments')
    op.drop_index(op.f('ix_dept_departments_id'), table_name='dept_departments')
    op.drop_index(op.f('ix_dept_departments_created_by'), table_name='dept_departments')
    op.drop_table('dept_departments')
    # ### end Alembic commands ###
