"""init

Revision ID: dbca43f18ede
Revises: 
Create Date: 2026-09-02 16:28:03.272061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbca43f18ede'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('script',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_executions_created_by'), 'script_executions', ['created_by'], unique=False)
    op.create_index(op.f('ix_script_executions_executor_id'), 'script_executions', ['executor_id'], unique=False)
    op.create_index(op.f('ix_script_executions_id'), 'script_executions', ['id'], unique=False)
    op.create_index(op.f('ix_script_executions_script_id'), 'script_executions', ['script_id'], unique=False)
    op.create_table('script_scripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_script_scripts_created_by'), 'script_scripts', ['created_by'], unique=False)
    op.create_index(op.f('ix_script_scripts_id'), 'script_scripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_scripts_id'), table_name='script_scripts')
    op.drop_index(op.f('ix_script_scripts_created_by'), table_name='script_scripts')
    op.drop_table('script_scripts')
    op.drop_index(op.f('ix_script_executions_script_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_executor_id'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_created_by'), table_name='script_executions')
    op.drop_table('script_executions')
    # ### end Alembic commands ###
