"""init

Revision ID: 5b5adbb8f211
Revises: 
Create Date: 2026-09-02 16:28:09.569074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b5adbb8f211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('user',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('status', postgresql.ENUM('ON', 'OFF', 'PENDING', name='status', create_type=False), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_users_created_by'), 'user_users', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_users_department_id'), 'user_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_users_id'), 'user_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_users_id'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_department_id'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_created_by'), table_name='user_users')
    op.drop_table('user_users')
    # ### end Alembic commands ###
