"""e.g. add user table

Revision ID: bed0bf42a8fc
Revises: 
Create Date: 2026-08-21 16:49:45.984599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bed0bf42a8fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('user',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
