"""init

Revision ID: 3b27d2210f22
Revises: 
Create Date: 2026-09-02 16:28:06.440804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b27d2210f22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('system',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_activity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Enum('task', 'user', 'system', 'alert', name='activitycategory', native_enum=False), nullable=False),
    sa.Column('event_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('level', sa.Enum('info', 'success', 'warning', 'error', name='activitylevel', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('title_key', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('title_params', sa.JSON(), nullable=False),
    sa.Column('description_key', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('description_params', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_system_activity_source_event_id')
    )
    op.create_index(op.f('ix_system_activity_events_actor_id'), 'system_activity_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_system_activity_events_category'), 'system_activity_events', ['category'], unique=False)
    op.create_index(op.f('ix_system_activity_events_created_by'), 'system_activity_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_activity_events_event_code'), 'system_activity_events', ['event_code'], unique=False)
    op.create_index(op.f('ix_system_activity_events_id'), 'system_activity_events', ['id'], unique=False)
    op.create_index(op.f('ix_system_activity_events_level'), 'system_activity_events', ['level'], unique=False)
    op.create_index(op.f('ix_system_activity_events_occurred_at'), 'system_activity_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_system_activity_events_subject_type'), 'system_activity_events', ['subject_type'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', name='auditresult', native_enum=False), nullable=False),
    sa.Column('risk_level', sa.Enum('normal', 'sensitive', 'critical', name='auditrisklevel', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('http', 'domain_event', 'system', name='auditsource', native_enum=False), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('request_summary', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_action'), 'system_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_actor_id'), 'system_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_correlation_id'), 'system_audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_created_by'), 'system_audit_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_id'), 'system_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_occurred_at'), 'system_audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_request_id'), 'system_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_resource_type'), 'system_audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_result'), 'system_audit_logs', ['result'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_risk_level'), 'system_audit_logs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_source'), 'system_audit_logs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_audit_logs_source'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_risk_level'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_result'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_resource_type'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_request_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_occurred_at'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_created_by'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_correlation_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_actor_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_action'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_system_activity_events_subject_type'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_occurred_at'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_level'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_id'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_event_code'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_created_by'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_category'), table_name='system_activity_events')
    op.drop_index(op.f('ix_system_activity_events_actor_id'), table_name='system_activity_events')
    op.drop_table('system_activity_events')
    # ### end Alembic commands ###
